# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.13
    resource_class: xlarge
    steps:
      - add_ssh_keys:
          fingerprints:
            - "f0:cd:94:74:e7:89:5a:27:39:db:bd:3d:73:ad:51:89"
      - checkout
      - run:
          name: Tools install
          command: |
            curl https://glide.sh/get | sh
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.24.0
            free -m
            df -lh
      - run:
          name: Env set up
          command: |
            export GO111MODULE=on
            export GOPRIVATE=github.com/coinexchain/*
            export GOROOT=$(go env GOROOT)
            export PATH=$PATH:$HOME/gopath/bin
      - run:
          name: Project proceed
          command: |
            ls -al
            go get golang.org/x/tools/cmd/cover
            go get github.com/mattn/goveralls
            go get golang.org/x/tools/cmd/goimports
            go mod tidy
            go mod vendor
            bash scripts/check.sh
            goveralls -coverprofile=coverage.out -service=circle-ci -repotoken=$repo_token



